version: '3.9'

services:
  geoserver:
    image: kartoza/geoserver:2.19.0
    ports:
      - '8080:8080'
    environment:
      - GEOSERVER_ADMIN_USER=${GEOSERVER_ADMIN_USER}
      - GEOSERVER_ADMIN_PASSWORD=${GEOSERVER_ADMIN_PASSWORD}
      - GEOSERVER_EXTENSIONS=postgis
    container_name: geoserver
    volumes:
      - ./data:/opt/geoserver/data_dir
    links:
      - postgres

  postgres:
    # image: postgis/postgis:15-3.3
    image: mdillon/postgis
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /data/postgres
    container_name: postgresdb
    volumes:
      - ./data/postgis:/data/postgres

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - geoserver
      - postgres
    ports:
      - '80:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    links:
      - postgres
