version: '3.9'

services:
  geoserver:
    image: kartoza/geoserver:latest
    ports:
      - '8080:8080'
    environment:
      - GEOSERVER_ADMIN_USER=kartoza
      - GEOSERVER_ADMIN_PASSWORD=myawesomegeoserver
    volumes:
      - ./data:/opt/geoserver/data_dir
